In [1]:
import numpy as np
import pandas as pd
import glob

In [2]:
locn = "C:\\Users\\rangy\\Downloads\\Hydraulics-main\\features\\*.txt"
# find all the txt files in the path 
files = glob.glob(locn)
# use a dict to save all the variables 
features = {}

In [3]:
for name in files:
    try:
        with open(name) as f:
            # read in the data 
            temp_df = pd.read_csv(name,delim_whitespace=True,header=None)
            # make the row names cycle as a variable
            temp_df.index.name = 'cycle'
            temp_df.reset_index(inplace=True)
            # transpose the data 
            temp_df_transposed= temp_df.T
            # make the seconds a variable, call it "time‚Äù
            temp_df_transposed.index.name = 'time'
            temp_df_transposed.reset_index(inplace=True)
            # add a prefix cycle in the column names to help with pivoting data (from wide to long)
            string = ' cycle'.join(str(e) for e in list(temp_df_transposed.columns))
            temp_df_transposed.columns = string.split(" ")
            # From wide to long to help with joining all the variables 
            temp_df_long = pd.wide_to_long(temp_df_transposed.iloc[1:,:],stubnames='cycle', i=['time'], j='c')
            temp_df_long.reset_index(inplace=True)
            # save each data variable in the long format into separate data frames in the dictionary called "features"
            # but exclude path and txt in the names
            features[name[9:-4]] = temp_df_long
                        
           
    
    # prevent a possible error
    except IOError as exc:
        if exc.errno != errno.EISDIR:
            raise

In [4]:
temp_df

time,cycle,0,1,2,3,4,5,6,7,8,...,50,51,52,53,54,55,56,57,58,59
0,0,0.604,0.605,0.611,0.603,0.608,0.608,0.608,0.617,0.619,...,0.554,0.552,0.545,0.553,0.553,0.539,0.544,0.545,0.535,0.543
1,1,0.590,0.610,0.626,0.620,0.623,0.619,0.617,0.618,0.619,...,0.555,0.547,0.548,0.544,0.536,0.542,0.540,0.533,0.531,0.534
2,2,0.578,0.603,0.638,0.651,0.652,0.662,0.662,0.656,0.652,...,0.543,0.544,0.543,0.554,0.544,0.544,0.545,0.544,0.530,0.534
3,3,0.565,0.591,0.608,0.614,0.623,0.645,0.642,0.645,0.642,...,0.549,0.538,0.553,0.543,0.553,0.555,0.544,0.543,0.543,0.542
4,4,0.570,0.600,0.623,0.636,0.644,0.642,0.651,0.654,0.660,...,0.546,0.546,0.544,0.552,0.539,0.540,0.549,0.542,0.533,0.537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2200,2200,0.558,0.584,0.600,0.602,0.617,0.617,0.618,0.613,0.618,...,0.532,0.526,0.521,0.515,0.518,0.519,0.518,0.525,0.522,0.527
2201,2201,0.566,0.569,0.577,0.578,0.577,0.573,0.577,0.578,0.578,...,0.534,0.535,0.529,0.526,0.531,0.536,0.541,0.536,0.530,0.544
2202,2202,0.566,0.562,0.561,0.567,0.576,0.580,0.575,0.585,0.590,...,0.533,0.526,0.527,0.521,0.509,0.516,0.516,0.512,0.515,0.517
2203,2203,0.529,0.539,0.552,0.552,0.550,0.553,0.567,0.560,0.560,...,0.538,0.527,0.524,0.522,0.514,0.519,0.526,0.522,0.520,0.528
2204,2204,0.541,0.553,0.565,0.578,0.575,0.591,0.590,0.591,0.599,...,0.538,0.535,0.534,0.524,0.522,0.516,0.528,0.522,0.522,0.531

In [5]:
temp_df_transposed

,time,cycle0,cycle1,cycle2,cycle3,cycle4,cycle5,cycle6,cycle7,cycle8,...,cycle2195,cycle2196,cycle2197,cycle2198,cycle2199,cycle2200,cycle2201,cycle2202,cycle2203,cycle2204
0,cycle,0.000,1.000,2.000,3.000,4.000,5.000,6.000,7.000,8.000,...,2195.000,2196.000,2197.000,2198.000,2199.000,2200.000,2201.000,2202.000,2203.000,2204.000
1,0,0.604,0.590,0.578,0.565,0.570,0.568,0.582,0.583,0.570,...,0.560,0.549,0.569,0.551,0.547,0.558,0.566,0.566,0.529,0.541
2,1,0.605,0.610,0.603,0.591,0.600,0.601,0.605,0.614,0.595,...,0.566,0.586,0.577,0.573,0.571,0.584,0.569,0.562,0.539,0.553
3,2,0.611,0.626,0.638,0.608,0.623,0.611,0.629,0.630,0.607,...,0.584,0.607,0.591,0.578,0.579,0.600,0.577,0.561,0.552,0.565
4,3,0.603,0.620,0.651,0.614,0.636,0.614,0.635,0.641,0.614,...,0.584,0.609,0.596,0.595,0.593,0.602,0.578,0.567,0.552,0.578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,55,0.539,0.542,0.544,0.555,0.540,0.539,0.530,0.542,0.544,...,0.543,0.526,0.531,0.516,0.525,0.519,0.536,0.516,0.519,0.516
57,56,0.544,0.540,0.545,0.544,0.549,0.543,0.525,0.530,0.535,...,0.534,0.528,0.520,0.516,0.525,0.518,0.541,0.516,0.526,0.528
58,57,0.545,0.533,0.544,0.543,0.542,0.547,0.524,0.533,0.532,...,0.550,0.527,0.515,0.518,0.516,0.525,0.536,0.512,0.522,0.522
59,58,0.535,0.531,0.530,0.543,0.533,0.546,0.525,0.530,0.531,...,0.539,0.523,0.509,0.524,0.520,0.522,0.530,0.515,0.520,0.522
60,59,0.543,0.534,0.534,0.542,0.537,0.554,0.537,0.548,0.533,...,0.535,0.525,0.531,0.528,0.529,0.527,0.544,0.517,0.528,0.531

In [6]:
len(features)

17

In [7]:
for key in list(features.keys()):
    features[key].columns=['seconds','cycle',key]

In [8]:
dfs= [features['rangy\\Downloads\\Hydraulics-main\\features\\CP'],
      features['rangy\\Downloads\\Hydraulics-main\\features\\CE'],
      features['rangy\\Downloads\\Hydraulics-main\\features\\EPS1'],
      features['rangy\\Downloads\\Hydraulics-main\\features\\FS1'],
      features['rangy\\Downloads\\Hydraulics-main\\features\\FS2'],
      features['rangy\\Downloads\\Hydraulics-main\\features\\PS1'],
      features['rangy\\Downloads\\Hydraulics-main\\features\\PS2'],
      features['rangy\\Downloads\\Hydraulics-main\\features\\PS3'],
      features['rangy\\Downloads\\Hydraulics-main\\features\\PS4'],
      features['rangy\\Downloads\\Hydraulics-main\\features\\PS5'],
      features['rangy\\Downloads\\Hydraulics-main\\features\\PS6'],
      features['rangy\\Downloads\\Hydraulics-main\\features\\SE'],
      features['rangy\\Downloads\\Hydraulics-main\\features\\TS1'],
      features['rangy\\Downloads\\Hydraulics-main\\features\\TS2'],
      features['rangy\\Downloads\\Hydraulics-main\\features\\TS3'],
      features['rangy\\Downloads\\Hydraulics-main\\features\\TS4'],
     features['rangy\\Downloads\\Hydraulics-main\\features\\VS1']]

In [9]:
from functools import reduce
features_join = reduce(lambda left,right: pd.merge(left,right,on=['seconds','cycle']), dfs)
features_join.head()

,seconds,cycle,rangy\Downloads\Hydraulics-main\features\CP,rangy\Downloads\Hydraulics-main\features\CE,rangy\Downloads\Hydraulics-main\features\EPS1,rangy\Downloads\Hydraulics-main\features\FS1,rangy\Downloads\Hydraulics-main\features\FS2,rangy\Downloads\Hydraulics-main\features\PS1,rangy\Downloads\Hydraulics-main\features\PS2,rangy\Downloads\Hydraulics-main\features\PS3,rangy\Downloads\Hydraulics-main\features\PS4,rangy\Downloads\Hydraulics-main\features\PS5,rangy\Downloads\Hydraulics-main\features\PS6,rangy\Downloads\Hydraulics-main\features\SE,rangy\Downloads\Hydraulics-main\features\TS1,rangy\Downloads\Hydraulics-main\features\TS2,rangy\Downloads\Hydraulics-main\features\TS3,rangy\Downloads\Hydraulics-main\features\TS4,rangy\Downloads\Hydraulics-main\features\VS1
0,0,0,2.184,47.202,2411.6,8.990,10.179,151.47,125.50,2.305,0.0,9.936,9.818,68.039,35.570,40.961,38.320,30.363,0.604
1,1,0,2.184,47.273,2411.6,0.770,10.174,151.45,125.39,2.305,0.0,9.947,9.823,0.000,35.492,40.949,38.332,30.375,0.605
2,2,0,2.184,47.250,2411.6,0.641,10.151,151.52,125.40,2.336,0.0,9.964,9.844,0.000,35.469,40.965,38.320,30.367,0.611
3,3,0,2.185,47.332,2411.6,0.006,10.149,151.27,125.03,2.578,0.0,9.989,9.861,0.000,35.422,40.922,38.324,30.367,0.603
4,4,0,2.178,47.213,2411.6,0.000,10.172,150.80,124.05,2.977,0.0,9.996,9.877,0.000,35.414,40.879,38.332,30.379,0.608

In [10]:
features_join.shape

(132300, 19)

In [11]:
label = pd.read_csv('profile.txt',delim_whitespace=True,header=None)
label.head()

   0    1  2    3  4
0  3  100  0  130  1
1  3  100  0  130  1
2  3  100  0  130  1
3  3  100  0  130  1
4  3  100  0  130  1

In [12]:
label.columns = ['cooler_condition', 'valve_condition', 'pump_leak', 'hydraulic_accumulator', 'stable_flag']

In [13]:
label.isna().sum()

cooler_condition         0
valve_condition          0
pump_leak                0
hydraulic_accumulator    0
stable_flag              0
dtype: int64

In [14]:
%pip install tsfresh

Requirement already satisfied: tsfresh in c:\users\rangy\anaconda3\lib\site-packages (0.17.0)
Requirement already satisfied: scipy>=1.2.0 in c:\users\rangy\anaconda3\lib\site-packages (from tsfresh) (1.5.2)
Requirement already satisfied: tqdm>=4.10.0 in c:\users\rangy\anaconda3\lib\site-packages (from tsfresh) (4.50.2)
Requirement already satisfied: dask[dataframe]>=2.9.0 in c:\users\rangy\anaconda3\lib\site-packages (from tsfresh) (2.30.0)
Requirement already satisfied: pandas>=0.25.0 in c:\users\rangy\anaconda3\lib\site-packages (from tsfresh) (1.1.3)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\rangy\anaconda3\lib\site-packages (from tsfresh) (0.12.0)
Requirement already satisfied: patsy>=0.4.1 in c:\users\rangy\anaconda3\lib\site-packages (from tsfresh) (0.5.1)
Requirement already satisfied: requests>=2.9.1 in c:\users\rangy\anaconda3\lib\site-packages (from tsfresh) (2.24.0)
Requirement already satisfied: scikit-learn>=0.19.2 in c:\users\rangy\anaconda3\lib\site-packages (from tsfresh) (0.23.2)
Requirement already satisfied: numpy>=1.15.1 in c:\users\rangy\anaconda3\lib\site-packages (from tsfresh) (1.19.2)
Requirement already satisfied: distributed>=2.11.0 in c:\users\rangy\anaconda3\lib\site-packages (from tsfresh) (2.30.1)
Requirement already satisfied: pyyaml in c:\users\rangy\anaconda3\lib\site-packages (from dask[dataframe]>=2.9.0->tsfresh) (5.3.1)
Requirement already satisfied: toolz>=0.8.2; extra == "dataframe" in c:\users\rangy\anaconda3\lib\site-packages (from dask[dataframe]>=2.9.0->tsfresh) (0.11.1)
Requirement already satisfied: partd>=0.3.10; extra == "dataframe" in c:\users\rangy\anaconda3\lib\site-packages (from dask[dataframe]>=2.9.0->tsfresh) (1.1.0)
Requirement already satisfied: fsspec>=0.6.0; extra == "dataframe" in c:\users\rangy\anaconda3\lib\site-packages (from dask[dataframe]>=2.9.0->tsfresh) (0.8.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\rangy\anaconda3\lib\site-packages (from pandas>=0.25.0->tsfresh) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\rangy\anaconda3\lib\site-packages (from pandas>=0.25.0->tsfresh) (2020.1)
Requirement already satisfied: six in c:\users\rangy\anaconda3\lib\site-packages (from patsy>=0.4.1->tsfresh) (1.15.0)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\rangy\anaconda3\lib\site-packages (from requests>=2.9.1->tsfresh) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\rangy\anaconda3\lib\site-packages (from requests>=2.9.1->tsfresh) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in c:\users\rangy\anaconda3\lib\site-packages (from requests>=2.9.1->tsfresh) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rangy\anaconda3\lib\site-packages (from requests>=2.9.1->tsfresh) (2020.6.20)
Requirement already satisfied: joblib>=0.11 in c:\users\rangy\anaconda3\lib\site-packages (from scikit-learn>=0.19.2->tsfresh) (0.17.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\rangy\anaconda3\lib\site-packages (from scikit-learn>=0.19.2->tsfresh) (2.1.0)
Requirement already satisfied: tblib>=1.6.0 in c:\users\rangy\anaconda3\lib\site-packages (from distributed>=2.11.0->tsfresh) (1.7.0)
Requirement already satisfied: psutil>=5.0 in c:\users\rangy\anaconda3\lib\site-packages (from distributed>=2.11.0->tsfresh) (5.7.2)
Requirement already satisfied: msgpack>=0.6.0 in c:\users\rangy\anaconda3\lib\site-packages (from distributed>=2.11.0->tsfresh) (1.0.0)
Requirement already satisfied: click>=6.6 in c:\users\rangy\anaconda3\lib\site-packages (from distributed>=2.11.0->tsfresh) (7.1.2)
Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in c:\users\rangy\anaconda3\lib\site-packages (from distributed>=2.11.0->tsfresh) (2.2.2)
Requirement already satisfied: zict>=0.1.3 in c:\users\rangy\anaconda3\lib\site-packages (from distributed>=2.11.0->tsfresh) (2.0.0)
Requirement already satisfied: tornado>=6.0.3; python_version >= "3.8" in c:\users\rangy\anaconda3\lib\site-packages (from distributed>=2.11.0->tsfresh) (6.0.4)
Requirement already satisfied: setuptools in c:\users\rangy\anaconda3\lib\site-packages (from distributed>=2.11.0->tsfresh) (50.3.1.post20201107)
Requirement already satisfied: cloudpickle>=1.5.0 in c:\users\rangy\anaconda3\lib\site-packages (from distributed>=2.11.0->tsfresh) (1.6.0)
Requirement already satisfied: locket in c:\users\rangy\anaconda3\lib\site-packages (from partd>=0.3.10; extra == "dataframe"->dask[dataframe]>=2.9.0->tsfresh) (0.2.0)
Requirement already satisfied: heapdict in c:\users\rangy\anaconda3\lib\site-packages (from zict>=0.1.3->distributed>=2.11.0->tsfresh) (1.0.1)
Note: you may need to restart the kernel to use updated packages.

In [15]:
import xgboost
from xgboost import XGBClassifier, XGBRegressor

xgc = XGBClassifier()
xgr = XGBRegressor()


from tsfresh.transformers import RelevantFeatureAugmenter
from sklearn.pipeline import Pipeline

import joblib

In [16]:
def preprocess_accum(ddf):
    ddf.index.name = 'cycle'
    ddf = pd.DataFrame(ddf)
    ddf.reset_index(inplace=True)
    # transpose the data 
    ddf_transposed= ddf.T
    # make the seconds a variable, call it "time‚Äù
    ddf_transposed.index.name = 'time'
    ddf_transposed.reset_index(inplace=True)
    # add a prefix cycle in the column names to help with pivoting data (from wide to long)
    string = ' cycle'.join(str(e) for e in list(ddf_transposed.columns))
    ddf_transposed.columns = string.split(" ")
    # From wide to long to help with joining all the variables 
    ddf_long = pd.wide_to_long(ddf_transposed.iloc[1:,:],stubnames='cycle', i=['time'], j='c')
    ddf_long.reset_index(inplace=True)
    # save each data variable in the long format into separate data frames in the dictionary called "features"
    # but exclude path and txt in the names
    features[name[9:-4]] = ddf_long   
    # prevent a possible error
    for key in list(features.keys()):
        features[key].columns=['seconds','cycle',key]
        
       
    return features

In [17]:
pipeline = Pipeline([('augmenter', RelevantFeatureAugmenter(column_id="cycle", column_sort="seconds")),
            ('xgb', XGBRegressor())])

In [18]:
from tsfresh.examples import download_robot_execution_failures
download_robot_execution_failures()

In [19]:
df_ts, y = load_robot_execution_failures()

NameError: name 'load_robot_execution_failures' is not defined

In [20]:
y_stable_flag = label['stable_flag']
y_stable_flag

0       1
1       1
2       1
3       1
4       1
       ..
2200    0
2201    0
2202    0
2203    0
2204    0
Name: stable_flag, Length: 2205, dtype: int64

In [21]:
X = pd.DataFrame(index = y_stable_flag.index)

In [22]:
pipeline.set_params(augmenter__timeseries_container=features_join)

Pipeline(steps=[('augmenter',
                 RelevantFeatureAugmenter(column_id='cycle',
                                          column_sort='seconds',
                                          timeseries_container=        seconds  cycle  rangy\Downloads\Hydraulics-main\features\CP  \
0             0      0                                        2.184
1             1      0                                        2.184
2             2      0                                        2.184
3             3      0                                        2.185
4             4      0                                        2.178
...         ...    ...                                          ...
132295       55   2204                                        2.134
132296       56   2204                                        2.146
132297       57   2204                                        2.144
132298       58   2204                                        2.136
132299       59   2204                                        2.148

        rangy\Downloads\Hydraulics-main\features\C...
                              importance_type='gain',
                              interaction_constraints=None, learning_rate=None,
                              max_delta_step=None, max_depth=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, n_estimators=100,
                              n_jobs=None, num_parallel_tree=None,
                              random_state=None, reg_alpha=None,
                              reg_lambda=None, scale_pos_weight=None,
                              subsample=None, tree_method=None,
                              validate_parameters=None, verbosity=None))])

In [23]:
pipeline.fit(X,y_stable_flag)

Feature Extraction: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 15/15 [11:47<00:00, 47.16s/it]
C:\Users\rangy\anaconda3\lib\site-packages\tsfresh\utilities\dataframe_functions.py:171: RuntimeWarning: The columns ['rangy\\Downloads\\Hydraulics-main\\features\\CP__fft_coefficient__attr_"real"__coeff_31'
 'rangy\\Downloads\\Hydraulics-main\\features\\CP__fft_coefficient__attr_"real"__coeff_32'
 'rangy\\Downloads\\Hydraulics-main\\features\\CP__fft_coefficient__attr_"real"__coeff_33'
 ...
 'rangy\\Downloads\\Hydraulics-main\\features\\VS1__fft_coefficient__attr_"angle"__coeff_97'
 'rangy\\Downloads\\Hydraulics-main\\features\\VS1__fft_coefficient__attr_"angle"__coeff_98'
 'rangy\\Downloads\\Hydraulics-main\\features\\VS1__fft_coefficient__attr_"angle"__coeff_99'] did not have any finite values. Filling with zeros.
  warnings.warn("The columns {} did not have any finite values. Filling with zeros.".format(

Pipeline(steps=[('augmenter',
                 RelevantFeatureAugmenter(column_id='cycle',
                                          column_sort='seconds',
                                          timeseries_container=        seconds  cycle  rangy\Downloads\Hydraulics-main\features\CP  \
0             0      0                                        2.184
1             1      0                                        2.184
2             2      0                                        2.184
3             3      0                                        2.185
4             4      0                                        2.178
...         ...    ...                                          ...
132295       55   2204                                        2.134
132296       56   2204                                        2.146
132297       57   2204                                        2.144
132298       58   2204                                        2.136
132299       59   2204                                        2.148

        rangy\Downloads\Hydraulics-main\features\C...
                              colsample_bytree=1, gamma=0, gpu_id=-1,
                              importance_type='gain',
                              interaction_constraints='',
                              learning_rate=0.300000012, max_delta_step=0,
                              max_depth=6, min_child_weight=1, missing=nan,
                              monotone_constraints='()', n_estimators=100,
                              n_jobs=6, num_parallel_tree=1, random_state=0,
                              reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
                              subsample=1, tree_method='exact',
                              validate_parameters=1, verbosity=None))])

In [30]:
type(y_stable_flag.index)

pandas.core.indexes.range.RangeIndex

In [45]:
xtest = np.arange(2204,2225,1)
xtest_df = pd.DataFrame(xtest)
xtest_df.set_index(xtest,inplace=True)
Xtest_df = pd.DataFrame(index = xtest_df.index)

In [46]:
pipeline.predict(Xtest_df)

Feature Extraction: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 9/9 [00:02<00:00,  4.03it/s]

array([0.00027919, 0.12936646, 0.12936646, 0.12936646, 0.12936646,
       0.12936646, 0.12936646, 0.12936646, 0.12936646, 0.12936646,
       0.12936646, 0.12936646, 0.12936646, 0.12936646, 0.12936646,
       0.12936646, 0.12936646, 0.12936646, 0.12936646, 0.12936646,
       0.12936646], dtype=float32)

In [47]:
joblib.dump(pipeline,'best_timeseries_pipeline.sav')

['best_timeseries_pipeline.sav']

In [38]:
X

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[2205 rows x 0 columns]

# Practicing time series forecasting by typing and testing

In [24]:
import pandas as pd
df = pd.DataFrame({
   "id": [1, 1, 1, 1, 2, 2],
   "time": [1, 2, 3, 4, 8, 9],
   "x": [1, 2, 3, 4, 10, 11],
   "y": [5, 6, 7, 8, 12, 13],
})

In [25]:
df

   id  time   x   y
0   1     1   1   5
1   1     2   2   6
2   1     3   3   7
3   1     4   4   8
4   2     8  10  12
5   2     9  11  13

In [26]:
features_join

,seconds,cycle,rangy\Downloads\Hydraulics-main\features\CP,rangy\Downloads\Hydraulics-main\features\CE,rangy\Downloads\Hydraulics-main\features\EPS1,rangy\Downloads\Hydraulics-main\features\FS1,rangy\Downloads\Hydraulics-main\features\FS2,rangy\Downloads\Hydraulics-main\features\PS1,rangy\Downloads\Hydraulics-main\features\PS2,rangy\Downloads\Hydraulics-main\features\PS3,rangy\Downloads\Hydraulics-main\features\PS4,rangy\Downloads\Hydraulics-main\features\PS5,rangy\Downloads\Hydraulics-main\features\PS6,rangy\Downloads\Hydraulics-main\features\SE,rangy\Downloads\Hydraulics-main\features\TS1,rangy\Downloads\Hydraulics-main\features\TS2,rangy\Downloads\Hydraulics-main\features\TS3,rangy\Downloads\Hydraulics-main\features\TS4,rangy\Downloads\Hydraulics-main\features\VS1
0,0,0,2.184,47.202,2411.6,8.990,10.179,151.47,125.500,2.305,0.000,9.936,9.818,68.039,35.570,40.961,38.320,30.363,0.604
1,1,0,2.184,47.273,2411.6,0.770,10.174,151.45,125.390,2.305,0.000,9.947,9.823,0.000,35.492,40.949,38.332,30.375,0.605
2,2,0,2.184,47.250,2411.6,0.641,10.151,151.52,125.400,2.336,0.000,9.964,9.844,0.000,35.469,40.965,38.320,30.367,0.611
3,3,0,2.185,47.332,2411.6,0.006,10.149,151.27,125.030,2.578,0.000,9.989,9.861,0.000,35.422,40.922,38.324,30.367,0.603
4,4,0,2.178,47.213,2411.6,0.000,10.172,150.80,124.050,2.977,0.000,9.996,9.877,0.000,35.414,40.879,38.332,30.379,0.608
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132295,55,2204,2.134,46.355,2652.0,0.001,10.179,186.38,0.562,0.000,10.235,9.999,9.873,68.167,35.441,40.910,38.195,30.395,0.516
132296,56,2204,2.146,46.432,2667.0,0.000,10.183,187.20,0.555,0.000,10.198,9.976,9.861,68.167,35.437,40.895,38.184,30.391,0.528
132297,57,2204,2.144,46.384,2690.8,0.000,10.198,187.80,0.484,0.000,10.191,9.960,9.837,68.258,35.434,40.883,38.184,30.395,0.522
132298,58,2204,2.136,46.479,2698.4,0.003,10.190,188.05,0.453,0.000,10.189,9.955,9.827,68.258,35.434,40.879,38.184,30.402,0.522
132299,59,2204,2.148,46.621,2710.4,0.001,10.199,188.34,0.445,0.000,10.173,9.960,9.831,68.117,35.426,40.891,38.187,30.375,0.531

In [27]:
from tsfresh.utilities.dataframe_functions import roll_time_series
df_rolled = roll_time_series(df, column_id="id", column_sort="time")

Rolling: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 4/4 [00:02<00:00,  1.91it/s]

In [28]:
from tsfresh import extract_features
df_features = extract_features(df_rolled, column_id="id", column_sort="time")

Feature Extraction: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 12/12 [00:02<00:00,  4.88it/s]

In [29]:
df_rolled

        id  time   x   y
3   (1, 1)     1   1   5
5   (1, 2)     1   1   5
6   (1, 2)     2   2   6
0   (1, 3)     1   1   5
1   (1, 3)     2   2   6
2   (1, 3)     3   3   7
9   (1, 4)     1   1   5
10  (1, 4)     2   2   6
11  (1, 4)     3   3   7
12  (1, 4)     4   4   8
4   (2, 8)     8  10  12
7   (2, 9)     8  10  12
8   (2, 9)     9  11  13

In [30]:
df_features

     x__variance_larger_than_standard_deviation  x__has_duplicate_max  \
1 1                                         0.0                   0.0
  2                                         0.0                   0.0
  3                                         0.0                   0.0
  4                                         1.0                   0.0
2 8                                         0.0                   0.0
  9                                         0.0                   0.0

     x__has_duplicate_min  x__has_duplicate  x__sum_values  x__abs_energy  \
1 1                   0.0               0.0            1.0            1.0
  2                   0.0               0.0            3.0            5.0
  3                   0.0               0.0            6.0           14.0
  4                   0.0               0.0           10.0           30.0
2 8                   0.0               0.0           10.0          100.0
  9                   0.0               0.0           21.0          221.0

     x__mean_abs_change  x__mean_change  x__mean_second_derivative_central  \
1 1                 NaN             NaN                                NaN
  2                 1.0             1.0                                NaN
  3                 1.0             1.0                                0.0
  4                 1.0             1.0                                0.0
2 8                 NaN             NaN                                NaN
  9                 1.0             1.0                                NaN

     x__median  ...  y__fourier_entropy__bins_2  y__fourier_entropy__bins_3  \
1 1        1.0  ...                         NaN                         NaN
  2        1.5  ...                   -0.000000                   -0.000000
  3        2.0  ...                    0.693147                    0.693147
  4        2.5  ...                    0.636514                    1.098612
2 8       10.0  ...                         NaN                         NaN
  9       10.5  ...                   -0.000000                   -0.000000

     y__fourier_entropy__bins_5  y__fourier_entropy__bins_10  \
1 1                         NaN                          NaN
  2                   -0.000000                    -0.000000
  3                    0.693147                     0.693147
  4                    1.098612                     1.098612
2 8                         NaN                          NaN
  9                   -0.000000                    -0.000000

     y__fourier_entropy__bins_100  y__permutation_entropy__dimension_3__tau_1  \
1 1                           NaN                                         NaN
  2                     -0.000000                                         NaN
  3                      0.693147                                        -0.0
  4                      1.098612                                        -0.0
2 8                           NaN                                         NaN
  9                     -0.000000                                         NaN

     y__permutation_entropy__dimension_4__tau_1  \
1 1                                         NaN
  2                                         NaN
  3                                         NaN
  4                                        -0.0
2 8                                         NaN
  9                                         NaN

     y__permutation_entropy__dimension_5__tau_1  \
1 1                                         NaN
  2                                         NaN
  3                                         NaN
  4                                         NaN
2 8                                         NaN
  9                                         NaN

     y__permutation_entropy__dimension_6__tau_1  \
1 1                                         NaN
  2                                         NaN
  3                                         NaN
  4                                         NaN
2 8                                         NaN
  9                                         NaN

     y__permutation_entropy__dimension_7__tau_1
1 1                                         NaN
  2                                         NaN
  3                                         NaN
  4                                         NaN
2 8                                         NaN
  9                                         NaN

[6 rows x 1558 columns]

In [32]:
df

   id  time   x   y
0   1     1   1   5
1   1     2   2   6
2   1     3   3   7
3   1     4   4   8
4   2     8  10  12
5   2     9  11  13

In [34]:
singular_time_series = df['x']
type(singular_time_series)

pandas.core.series.Series

In [35]:
from tsfresh.utilities.dataframe_functions import make_forecasting_frame

In [38]:
df_shift,y = make_forecasting_frame(x=singular_time_series,kind='price',max_timeshift=2,rolling_direction=1)

Rolling: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 6/6 [00:02<00:00,  2.85it/s]

In [39]:
df_shift

         id  time  value   kind
0   (id, 1)     0      1  price
2   (id, 2)     0      1  price
3   (id, 2)     1      2  price
12  (id, 3)     1      2  price
13  (id, 3)     2      3  price
9   (id, 4)     2      3  price
10  (id, 4)     3      4  price
6   (id, 5)     3      4  price
7   (id, 5)     4     10  price

In [40]:
y

1     2
2     3
3     4
4    10
5    11
Name: value, dtype: int64